# Lets get started by import numpy 





In [48]:
import math
import numpy
 

# Notes on Python


#### Numpy is used to solve more complex math problems with arrays, linear algebra, and other functions


Numpy provides a faster and easier way to make and read arrays

below is an array made with python

In [49]:
In [1]: matrix = [[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]]
In [2]: [[i + 1 for i in row] for row in matrix]
Out[2]: [[2, 3, 4], [5, 6, 7], [8, 9, 10]]


Below is a 2D array made with numpy


In [50]:
In [3]: # type: ignore # First, let's import NumPy
import numpy as np
In [4]: # type: ignore # Constructing an array with a simple list results in a 1d array
array1 = np.array([10, 100, 1000.])
In [5]: # type: ignore # Constructing an array with a nested list results in a 2d array
array2 = np.array([[1., 2., 3.],
                           [4., 5., 6.]])

Float64 - a default value of numpy that can store integers and strings
 this is very useful and saves time especially in arrays 

 If you do not want the default value given by numpy and instead want a python data type you can do so by writing out in python

 example below

In [51]:
In[6]: int (array1[0])
Out[7]: 10


Vectorization - when numpy does an operational sequence that would usually require a loop but not in this case
Vectorization will loop through a command by its self( no more for( int i; 0 i < array.length; i++>))

In [52]:
In [8]: array2 + 1


array([[2., 3., 4.],
       [5., 6., 7.]])

Broadcasting - numpy method of combining arrays with mathematic operations
Broadcasting fits the smaller array into the bigger one
it essentially picks out parts of an arrya to use
distributing one array to another

To multiply arrays use the @ symbol as demonstrated below

In [53]:
In [11]: array2 @ array2.T  # array2.T is a shortcut for array2.transpose()


array([[14., 32.],
       [32., 77.]])

Universal Function - numpy method that makes a given change to each object in the array
only sorks with numpy function names

The first code is waht not to do, and the second is what you should do

In [54]:
In [13]: math.sqrt(array2)  # This will raise en Error

TypeError: only length-1 arrays can be converted to Python scalars

In [ ]:
In [15]: np.sqrt(array2)


array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

Axis=0 is to get a 1d array ( the first coloumn in a 2d array)
when axis=1 is called, the first row of a 2d array is called

using axis= 0 returns an array

In [ ]:
Out[16]: array([5., 7., 9.])


using axis=1 or 2 returns a row from given array
(row is going from left to right on y axis)

In [ ]:
In [16]: array2.sum(axis=1)

array([ 6., 15.])

# Array manipulation

chain indexing - numpy method for calling a specific element from an array
(2d array example)

In [ ]:
numpy_array[row_selection, column_selection]

scalar - returned element from an array

slice notation allows you to manipute which elements from an array get selected, and what they can turn into
wheter that be a scalar,1d array, or 2d array

you can skip the first coloumn by having the slicer start at 1 for coloumn
example [:, 1:]

the first colon represents all rows( left to right)
the second colon represents start at row 1 and go on until the end(up down starting from left)


if more than 1 row or column is present, the return value will be a 2d array

arange - numpy method for range

reshape - method that allows you to choose the dimensions of the given array

The following code snippet gets the range for 10 with arange using a 2 by 5 2d array made with parameters only

In [ ]:
In [23]: np.arange(2 * 5).reshape(2, 5)


# View vs Copy

view - gives you part of an array
if you edit a view, you edit the orginial array

In [ ]:
In [26]: subset = array2[:, :2]
         subset

In order to leave the orginial array untouched by whatever changes you make to the subsset, you need to make a copy 

In [ ]:
subset = array2[:, :2].copy()


Note - numpy arrays must be the same data type